// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aya
{
    internal sealed partial class Vsix
    {
        public const string Id = "Aya.31d3531e-cb30-43c0-8483-f7e5a446d600";
        public const string Name = "Aya";
        public const string Description = @"This extension reminds the user of quran by showing a verse (Aya) from quran every once in a while.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "mohab mohammad";
        public const string Tags = "";
    }
}
